Repository Library-solider/codesquad-library, pull requests merged in 2020-11, with the labels that each got.

#171 대여하기 요청시 유저 권한 확인하는 기능
  src/main/java/com/librarycodesquad/prod/controller/AccountController.java
  src/main/java/com/librarycodesquad/prod/domain/account/Account.java
  src/main/java/com/librarycodesquad/prod/global/config/SecurityConfig.java
  src/main/java/com/librarycodesquad/prod/service/AccountService.java
Labels: Server

#173 [#172] feat: 로그아웃 기능 추가
  src/main/java/com/librarycodesquad/prod/controller/AccountController.java
  src/main/java/com/librarycodesquad/prod/global/config/SecurityConfig.java
Labels: Server

#176 [#174] fix: 도서 대여 목록 반납일자 빠른순으로 정렬.
  src/main/java/com/librarycodesquad/admin/service/BookAdminService.java
Labels: HotFix

#177 대여중인 도서와 대여중인 회원 정보 조회 기능 구현 완료
  src/main/java/com/librarycodesquad/admin/domain/book/response/BookDetailResponse.java
  src/main/java/com/librarycodesquad/prod/domain/rental/Rental.java
  src/main/resources/static/css/details-account.css
  src/main/resources/templates/account/details-account.html
  src/main/resources/templates/book/books-detail.html
Labels: Admin
