Repository Library-solider/codesquad-library, pull requests merged in 2020-09, with the labels that each got.

#90 [#83] feat: 마이페이지 API 추가 및 도서 대여수 수정.
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
  src/main/java/kr/codesquad/library/domain/account/response/AccountProfileResponse.java
  src/main/java/kr/codesquad/library/domain/rental/response/RentalBookResponse.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/test/java/kr/codesquad/library/service/AccountServiceTest.java
  src/test/java/kr/codesquad/library/service/BookServiceTest.java
Labels: Server

#92 [#91] feat: 로그인용 프로필 아이디, 아바타이미지 API 기능 추가
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/domain/account/response/AccountProfileResponse.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/test/java/kr/codesquad/library/service/AccountServiceTest.java
Labels: Server

#94 [#93] fix: 대여를 한 도서를 다시 빌리고 반납할 때 버그 수정
  src/main/java/kr/codesquad/library/domain/rental/RentalRepository.java
  src/main/java/kr/codesquad/library/service/BookService.java
Labels: HotFix, Server

#97 [#95] fix: 로그인 프로필 500에러 수정 및 JWT 삭제
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
  src/main/java/kr/codesquad/library/global/config/oauth/dto/AccountPrincipal.java
  src/main/java/kr/codesquad/library/global/config/oauth/dto/GithubOAuth2UserInfo.java
  src/main/java/kr/codesquad/library/global/config/oauth/dto/OAuthAttributes.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/CustomOAuth2UserService.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/OAuth2SuccessHandler.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/ProviderAttributes.java
  src/main/java/kr/codesquad/library/global/error/ErrorCode.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/JwtNotFoundException.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/ProviderNotExistException.java
  src/main/java/kr/codesquad/library/global/utils/CookieUtils.java
  src/main/java/kr/codesquad/library/global/utils/JwtProvider.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: HotFix, Server

#99 [#98] refactor: 코드리뷰 배경으로 리팩토링 실행
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/controller/BookController.java
  src/main/java/kr/codesquad/library/domain/account/Account.java
  src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
  src/main/java/kr/codesquad/library/domain/book/Book.java
  src/main/java/kr/codesquad/library/domain/book/BookRepository.java
  src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
  src/main/java/kr/codesquad/library/domain/rental/Rental.java
  src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/CustomOAuth2UserService.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
  src/test/java/kr/codesquad/library/service/AccountServiceTest.java
  src/test/java/kr/codesquad/library/service/BookServiceTest.java
Labels: Refactoring, Server

#101 [#100] feat: 유저 권한 표시 및 권한 요청 API 추가
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/domain/account/Account.java
  src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
  src/main/java/kr/codesquad/library/domain/account/response/RoleRequestResponse.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/CustomOAuth2UserService.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/ProviderAttributes.java
  src/main/java/kr/codesquad/library/global/error/ErrorCode.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/BadRequestAuthorizationException.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/RedundantRequestBookException.java
  src/main/java/kr/codesquad/library/global/error/exception/oauth/ProviderNotExistException.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/test/java/kr/codesquad/library/service/AccountServiceTest.java
Labels: Server

#104 [#105] fix: 권한 요청 API 삭제
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/domain/account/Account.java
  src/main/java/kr/codesquad/library/domain/account/response/RoleRequestResponse.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/BadRequestAuthorizationException.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/test/java/kr/codesquad/library/service/AccountServiceTest.java
Labels: HotFix, Server

#105 [#105] fix: 컴파일러 에러 발견하여 수정
  src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/CustomOAuth2UserService.java
Labels: HotFix, Server

#107 [Server] 401, 403 에러처리 수정
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/controller/OpenApiController.java
  src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/CustomAccessDeniedHandler.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/CustomAuthenticationEntryPoint.java
  src/main/java/kr/codesquad/library/global/error/ErrorCode.java
  src/main/java/kr/codesquad/library/global/error/ErrorResponse.java
  src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
Labels: HotFix, Server

#112 [Server] 5차 리뷰바탕으로 코드 리팩토링
  deploy.sh
  src/main/java/kr/codesquad/library/controller/BookController.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/main/java/kr/codesquad/library/service/OpenApiService.java
  src/test/java/kr/codesquad/library/controller/AccountControllerTest.java
  src/test/java/kr/codesquad/library/controller/BookControllerTest.java
  src/test/java/kr/codesquad/library/service/BookServiceTest.java
Labels: Refactoring, Server

#102 [Server] 5번째 리뷰요청입니다.
  src/main/java/kr/codesquad/library/controller/AccountController.java
  src/main/java/kr/codesquad/library/controller/BookController.java
  src/main/java/kr/codesquad/library/domain/account/Account.java
  src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
  src/main/java/kr/codesquad/library/domain/account/response/RoleRequestResponse.java
  src/main/java/kr/codesquad/library/domain/book/Book.java
  src/main/java/kr/codesquad/library/domain/book/BookRepository.java
  src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
  src/main/java/kr/codesquad/library/domain/rental/Rental.java
  src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
  src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
  src/main/java/kr/codesquad/library/global/config/oauth/dto/AccountPrincipal.java
  src/main/java/kr/codesquad/library/global/config/oauth/dto/GithubOAuth2UserInfo.java
  src/main/java/kr/codesquad/library/global/config/oauth/dto/OAuthAttributes.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/CustomOAuth2UserService.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/OAuth2SuccessHandler.java
  src/main/java/kr/codesquad/library/global/config/oauth/security/ProviderAttributes.java
  src/main/java/kr/codesquad/library/global/error/ErrorCode.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/BadRequestAuthorizationException.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/JwtNotFoundException.java
  src/main/java/kr/codesquad/library/global/error/exception/domain/RedundantRequestBookException.java
  src/main/java/kr/codesquad/library/global/error/exception/oauth/ProviderNotExistException.java
  src/main/java/kr/codesquad/library/global/utils/CookieUtils.java
  src/main/java/kr/codesquad/library/global/utils/JwtProvider.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/main/resources/application.yml
  src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
  src/test/java/kr/codesquad/library/service/AccountServiceTest.java
  src/test/java/kr/codesquad/library/service/BookServiceTest.java
  src/test/resources/application.yml
Labels: Review, Server

#113 [Server] refactor: 복수형일 때 findAll로 변경.
  src/main/java/kr/codesquad/library/domain/book/BookRepository.java
  src/main/java/kr/codesquad/library/domain/rental/RentalRepository.java
  src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
  src/test/java/kr/codesquad/library/service/BookServiceTest.java
Labels: Refactoring, Server

#114 [#109] 권한 승인 대기 목록 API 구현 완료
  src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
  src/main/java/kr/codesquad/library/admin/domain/account/AccountAdminRepository.java
  src/main/java/kr/codesquad/library/admin/domain/account/AccountSummaryResponse.java
  src/main/java/kr/codesquad/library/admin/service/AccountAdminService.java
  src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/css/authorization.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/images/logo-with-title.png
  src/main/resources/static/images/logo.png
  src/main/resources/templates/authorization.html
  src/main/resources/templates/index.html
  src/test/java/kr/codesquad/library/admin/service/AccountAdminServiceTest.java
Labels: Admin, Review

#118 [Server] 도서 상세정보 도서위치 추가
  src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
  src/main/java/kr/codesquad/library/domain/book/Book.java
  src/main/java/kr/codesquad/library/domain/book/response/BookDetailResponse.java
  src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
  src/main/java/kr/codesquad/library/domain/book/response/BooksByCategoryResponse.java
  src/main/java/kr/codesquad/library/domain/bookcase/Bookcase.java
  src/main/java/kr/codesquad/library/domain/category/Category.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/test/java/kr/codesquad/library/domain/book/BookRepositoryTest.java
  src/test/java/kr/codesquad/library/service/BookServiceTest.java
Labels: HotFix, Server

#119 [#115] refactor: Dto of, from 메서드 역할을 잘못이해하여 재수정
  src/main/java/kr/codesquad/library/domain/account/response/AccountMyPageResponse.java
  src/main/java/kr/codesquad/library/domain/account/response/AccountProfileResponse.java
  src/main/java/kr/codesquad/library/domain/book/response/BookDetailResponse.java
  src/main/java/kr/codesquad/library/domain/book/response/BookResponse.java
  src/main/java/kr/codesquad/library/domain/book/response/BookSearchResponse.java
  src/main/java/kr/codesquad/library/domain/book/response/BooksByCategoryResponse.java
  src/main/java/kr/codesquad/library/domain/rental/Rental.java
  src/main/java/kr/codesquad/library/domain/rental/firstclass/Rentals.java
  src/main/java/kr/codesquad/library/service/AccountService.java
  src/main/java/kr/codesquad/library/service/BookService.java
  src/test/java/kr/codesquad/library/service/BookServiceTest.java
Labels: Refactoring, Server

#120 [#115] fix: account 엔티티 id 추가
  src/main/java/kr/codesquad/library/domain/account/Account.java
Labels: HotFix, Server

#123 [Admin] 회원 권한 승인 API 구현
  src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
  src/main/java/kr/codesquad/library/admin/domain/account/AccountAdminRepository.java
  src/main/java/kr/codesquad/library/admin/service/AccountAdminService.java
  src/main/java/kr/codesquad/library/domain/account/Account.java
  src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
  src/main/resources/static/css/main.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
  src/test/java/kr/codesquad/library/admin/service/AccountAdminServiceTest.java
Labels: Admin

#126 [#125] feat: 도서 대여 목록 필드값 추가 및 404 코드 변경
  src/main/java/kr/codesquad/library/domain/rental/response/RentalBookResponse.java
  src/main/java/kr/codesquad/library/global/error/ErrorCode.java
  src/main/java/kr/codesquad/library/global/error/GlobalRestExceptionHandler.java
Labels: Server

#127 [Admin] View 1차 수정 완료
  src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
  src/main/resources/application.yml
  src/main/resources/static/css/access-admin.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/ajaxRequest.js
  src/main/resources/templates/access-admin.html
  src/main/resources/templates/account/guest-accounts.html
Labels: Admin

#129 [#128] feat: 도서 대여 목록 저자 추가 및 대여일 삭제
  src/main/java/kr/codesquad/library/domain/rental/response/RentalBookResponse.java
  src/test/java/kr/codesquad/library/service/AccountServiceTest.java
Labels: Server

#131 [#130] documentation: 서버 리드미 추가. 사진은 추후에 추가됨.
  README.md
Labels: documentation

#132 [Admin] 회원 목록 조회 기능 구현
  src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
  src/main/java/kr/codesquad/library/admin/controller/AuthAdminController.java
  src/main/java/kr/codesquad/library/admin/domain/account/AccountAdminRepository.java
  src/main/java/kr/codesquad/library/admin/domain/account/AccountSummaryResponse.java
  src/main/java/kr/codesquad/library/admin/service/AccountAdminService.java
  src/main/java/kr/codesquad/library/global/config/SecurityConfig.java
  src/main/resources/static/js/ajaxRequest.js
  src/main/resources/templates/account/all-accounts.html
  src/main/resources/templates/account/guest-accounts.html
  src/test/java/kr/codesquad/library/admin/service/AccountAdminServiceTest.java
Labels: Admin

#137 [Admin] 회원 상세 정보 조회 기능 구현
  src/main/java/kr/codesquad/library/admin/controller/AccountAdminController.java
  src/main/java/kr/codesquad/library/admin/domain/account/AccountDetailsResponse.java
  src/main/java/kr/codesquad/library/admin/service/AccountAdminService.java
  src/main/resources/static/css/details-account.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/accountDataTableHandler.js
  src/main/resources/static/js/ajaxRequest.js
  src/main/resources/templates/account/all-accounts.html
  src/main/resources/templates/account/details-account.html
  src/main/resources/templates/account/guest-accounts.html
  src/test/java/kr/codesquad/library/admin/service/AccountAdminServiceTest.java
Labels: Admin

#138 [#130] documentation: 사진 추가 및 멤버 추가
  README.md
Labels: documentation
